use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Update via WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Code Usage Monitor",
    refresh: "Refresh",
    update_frequency: "Update Frequency",
    one_minute: "1 Minute",
    five_minutes: "5 Minutes",
    fifteen_minutes: "15 Minutes",
    one_hour: "1 Hour",
    models: "Models",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Settings",
    open_settings: "Settings…",
    start_with_windows: "Start with Windows",
    reset_position: "Reset Position",
    language: "Language",
    system_default: "System Default",
    check_for_updates: "Check for Updates",
    checking_for_updates: "Checking for Updates...",
    updates: "Updates",
    update_in_progress: "An update check is already in progress.",
    up_to_date: "You already have the latest version.",
    up_to_date_short: "Up to date",
    update_failed: "Unable to update automatically",
    applying_update: "Applying update...",
    update_to: "Update to",
    update_available: "Update available",
    update_prompt_now: "Version {version} is available. Do you want to update now?",
    exit: "Exit",
    show_widget: "Show Widget",
    session_window: "5h",
    weekly_window: "7d",
    now: "now",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    token_expired_title: "Claude Code Auth Error",
    token_expired_body: "Run 'claude' in a terminal, then use '/login' and follow the prompts. After that, refresh or restart this app.",
    codex_token_expired_title: "Codex Auth Error",
    codex_token_expired_body: "Run 'codex' in a terminal and follow the sign-in prompts. After that, refresh or restart this app.",
    antigravity_token_expired_title: "Antigravity Auth Error",
    antigravity_token_expired_body: "Open Antigravity and sign in again. After that, refresh or restart this app.",
    codex_window_title: "Codex Usage Monitor",
    antigravity_window_title: "Antigravity Usage Monitor",
    second_suffix: "s",
    section_appearance: "Appearance",
    section_font: "Font",
    section_size: "Size",
    section_animations: "Animations",
    section_update: "Update",
    section_presets: "Presets",
    color_calm: "Calm",
    color_attention: "Attention",
    color_critical: "Critical",
    color_background: "Background",
    color_text: "Text",
    color_divider: "Divider",
    frequency_custom: "Custom",
    preset_default: "Default",
    preset_glass: "Glass",
    preset_neon: "Neon",
    preset_minimal: "Minimal",
    weight_regular: "Regular",
    weight_semibold: "SemiBold",
    weight_bold: "Bold",
    geometry_height: "Height",
    geometry_corner_radius: "Corner Radius",
    geometry_bar_thickness: "Bar Thickness",
    geometry_label_width: "Label Width",
    geometry_text_width: "Text Width",
    geometry_spacing: "Spacing",
    field_opacity: "Opacity",
    field_family: "Family",
    field_size: "Size",
    field_weight: "Weight",
    field_on: "On",
    field_speed: "Speed",
    field_intensity: "Intensity",
    field_threshold: "Threshold",
    field_duration: "Duration",
    field_reduce_motion: "Reduce Motion",
    field_frequency: "Frequency",
    field_custom_minutes: "Custom (min)",
    group_fill: "Fill",
    group_shimmer: "Shimmer",
    group_alert_glow: "Alert Glow",
    group_fade_slide: "Fade / Slide",
    button_reset: "Reset",
    button_cancel: "Cancel",
    button_save: "Save",
    presets_intro: "Click a preset to apply it to Appearance and Animations below. Save to keep it, Cancel to discard.",
    rgba_custom: "Custom…",
    preset_category_builtin: "Built-in",
    preset_category_editors: "Code editors",
    preset_category_apps: "Apps",
};
