use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Bijwerken via WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Code Gebruiksmonitor",
    refresh: "Vernieuwen",
    update_frequency: "Updatefrequentie",
    one_minute: "1 minuut",
    five_minutes: "5 minuten",
    fifteen_minutes: "15 minuten",
    one_hour: "1 uur",
    models: "Modellen",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Instellingen",
    open_settings: "Instellingen…",
    start_with_windows: "Opstarten met Windows",
    reset_position: "Positie herstellen",
    language: "Taal",
    system_default: "Systeemstandaard",
    check_for_updates: "Controleren op updates",
    checking_for_updates: "Controleren op updates...",
    updates: "Updates",
    update_in_progress: "Er is al een updatecontrole bezig.",
    up_to_date: "Je gebruikt al de nieuwste versie.",
    up_to_date_short: "Up-to-date",
    update_failed: "Automatisch bijwerken mislukt",
    applying_update: "Update wordt toegepast...",
    update_to: "Bijwerken naar",
    update_available: "Update beschikbaar",
    update_prompt_now: "Versie {version} is beschikbaar. Wil je nu bijwerken?",
    exit: "Afsluiten",
    show_widget: "Widget tonen",
    session_window: "5u",
    weekly_window: "7d",
    now: "nu",
    day_suffix: "d",
    hour_suffix: "u",
    minute_suffix: "m",
    token_expired_title: "Claude Code-authenticatiefout",
    token_expired_body: "Voer 'claude' uit in een terminal, gebruik daarna '/login' en volg de stappen. Ververs of herstart de app daarna.",
    codex_token_expired_title: "Codex-authenticatiefout",
    codex_token_expired_body: "Voer 'codex' uit in een terminal en volg de aanmeldstappen. Ververs of herstart de app daarna.",
    antigravity_token_expired_title: "Antigravity-authenticatiefout",
    antigravity_token_expired_body: "Open Antigravity en meld je opnieuw aan. Ververs of herstart de app daarna.",
    codex_window_title: "Codex-gebruiksmonitor",
    antigravity_window_title: "Antigravity-gebruiksmonitor",
    second_suffix: "s",
    section_appearance: "Uiterlijk",
    section_font: "Lettertype",
    section_size: "Grootte",
    section_animations: "Animaties",
    section_update: "Update",
    section_presets: "Voorinstellingen",
    color_calm: "Rustig",
    color_attention: "Aandacht",
    color_critical: "Kritiek",
    color_background: "Achtergrond",
    color_text: "Tekst",
    color_divider: "Scheidingslijn",
    frequency_custom: "Aangepast",
    preset_default: "Standaard",
    preset_glass: "Glas",
    preset_neon: "Neon",
    preset_minimal: "Minimaal",
    weight_regular: "Normaal",
    weight_semibold: "Halfvet",
    weight_bold: "Vet",
    geometry_height: "Hoogte",
    geometry_corner_radius: "Hoekradius",
    geometry_bar_thickness: "Balkdikte",
    geometry_label_width: "Labelbreedte",
    geometry_text_width: "Tekstbreedte",
    geometry_spacing: "Afstand",
    field_opacity: "Dekking",
    field_family: "Familie",
    field_size: "Grootte",
    field_weight: "Gewicht",
    field_on: "Aan",
    field_speed: "Snelheid",
    field_intensity: "Intensiteit",
    field_threshold: "Drempel",
    field_duration: "Duur",
    field_reduce_motion: "Beweging beperken",
    field_frequency: "Frequentie",
    field_custom_minutes: "Aangepast (min)",
    group_fill: "Vulling",
    group_shimmer: "Glinstering",
    group_alert_glow: "Waarschuwingsgloed",
    group_fade_slide: "Vervagen / Schuiven",
    button_reset: "Herstellen",
    button_cancel: "Annuleren",
    button_save: "Opslaan",
    presets_intro: "Klik op een voorinstelling om deze toe te passen op Uiterlijk en Animaties hieronder. Opslaan om te bewaren, Annuleren om te verwerpen.",
    rgba_custom: "Aangepast…",
    preset_category_builtin: "Ingebouwd",
    preset_category_editors: "Code-editors",
    preset_category_apps: "Apps",
};
