use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Mettre à jour avec WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Moniteur d'utilisation Claude Code",
    refresh: "Actualiser",
    update_frequency: "Fréquence de mise à jour",
    one_minute: "1 minute",
    five_minutes: "5 minutes",
    fifteen_minutes: "15 minutes",
    one_hour: "1 heure",
    models: "Modeles",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Paramètres",
    open_settings: "Paramètres…",
    start_with_windows: "Démarrer avec Windows",
    reset_position: "Réinitialiser la position",
    language: "Langue",
    system_default: "Par défaut du système",
    check_for_updates: "Vérifier les mises à jour",
    checking_for_updates: "Vérification des mises à jour...",
    updates: "Mises à jour",
    update_in_progress: "Une vérification de mise à jour est déjà en cours.",
    up_to_date: "Vous utilisez déjà la version la plus récente.",
    up_to_date_short: "À jour",
    update_failed: "Impossible d'effectuer la mise à jour automatiquement",
    applying_update: "Application de la mise à jour...",
    update_to: "Mettre à jour vers",
    update_available: "Mise à jour disponible",
    update_prompt_now: "La version {version} est disponible. Voulez-vous mettre à jour maintenant ?",
    exit: "Quitter",
    show_widget: "Afficher le widget",
    session_window: "5h",
    weekly_window: "7d",
    now: "maintenant",
    day_suffix: "j",
    hour_suffix: "h",
    minute_suffix: "m",
    token_expired_title: "Erreur d'authentification",
    token_expired_body: "Exécutez 'claude' dans un terminal, puis utilisez '/login' et suivez les instructions. Ensuite, actualisez ou redémarrez cette application.",
    codex_token_expired_title: "Erreur d'authentification Codex",
    codex_token_expired_body: "Executez 'codex' dans un terminal et suivez les instructions de connexion. Ensuite, actualisez ou redemarrez cette application.",
    antigravity_token_expired_title: "Erreur d'authentification Antigravity",
    antigravity_token_expired_body: "Ouvrez Antigravity et reconnectez-vous. Ensuite, actualisez ou redemarrez cette application.",
    codex_window_title: "Moniteur d'utilisation Codex",
    antigravity_window_title: "Moniteur d'utilisation Antigravity",
    second_suffix: "s",
    section_appearance: "Apparence",
    section_font: "Police",
    section_size: "Taille",
    section_animations: "Animations",
    section_update: "Mise à jour",
    section_presets: "Préréglages",
    color_calm: "Calme",
    color_attention: "Attention",
    color_critical: "Critique",
    color_background: "Arrière-plan",
    color_text: "Texte",
    color_divider: "Séparateur",
    frequency_custom: "Personnalisé",
    preset_default: "Par défaut",
    preset_glass: "Verre",
    preset_neon: "Néon",
    preset_minimal: "Minimal",
    weight_regular: "Normal",
    weight_semibold: "Demi-gras",
    weight_bold: "Gras",
    geometry_height: "Hauteur",
    geometry_corner_radius: "Rayon des coins",
    geometry_bar_thickness: "Épaisseur de la barre",
    geometry_label_width: "Largeur de l'étiquette",
    geometry_text_width: "Largeur du texte",
    geometry_spacing: "Espacement",
    field_opacity: "Opacité",
    field_family: "Famille",
    field_size: "Taille",
    field_weight: "Graisse",
    field_on: "Activé",
    field_speed: "Vitesse",
    field_intensity: "Intensité",
    field_threshold: "Seuil",
    field_duration: "Durée",
    field_reduce_motion: "Réduire les animations",
    field_frequency: "Fréquence",
    field_custom_minutes: "Personnalisé (min)",
    group_fill: "Remplissage",
    group_shimmer: "Scintillement",
    group_alert_glow: "Lueur d'alerte",
    group_fade_slide: "Fondu / Glissement",
    button_reset: "Réinitialiser",
    button_cancel: "Annuler",
    button_save: "Enregistrer",
    presets_intro: "Cliquez sur un préréglage pour l'appliquer à Apparence et Animations ci-dessous. Enregistrer pour le conserver, Annuler pour l'abandonner.",
    rgba_custom: "Personnalisé…",
    preset_category_builtin: "Intégré",
    preset_category_editors: "Éditeurs de code",
    preset_category_apps: "Applications",
};
