use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Mit WinGet aktualisieren";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Code Nutzungsmonitor",
    refresh: "Aktualisieren",
    update_frequency: "Aktualisierungsintervall",
    one_minute: "1 Minute",
    five_minutes: "5 Minuten",
    fifteen_minutes: "15 Minuten",
    one_hour: "1 Stunde",
    models: "Modelle",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Einstellungen",
    open_settings: "Einstellungen…",
    start_with_windows: "Mit Windows starten",
    reset_position: "Position zurücksetzen",
    language: "Sprache",
    system_default: "Systemstandard",
    check_for_updates: "Nach Updates suchen",
    checking_for_updates: "Suche nach Updates...",
    updates: "Updates",
    update_in_progress: "Eine Update-Prüfung läuft bereits.",
    up_to_date: "Sie verwenden bereits die neueste Version.",
    up_to_date_short: "Aktuell",
    update_failed: "Automatisches Update war nicht möglich",
    applying_update: "Update wird installiert...",
    update_to: "Aktualisieren auf",
    update_available: "Update verfügbar",
    update_prompt_now: "Version {version} ist verfügbar. Möchten Sie jetzt aktualisieren?",
    exit: "Beenden",
    show_widget: "Widget anzeigen",
    session_window: "5h",
    weekly_window: "7d",
    now: "jetzt",
    day_suffix: "T",
    hour_suffix: "h",
    minute_suffix: "m",
    token_expired_title: "Authentifizierungsfehler",
    token_expired_body: "Führen Sie 'claude' in einem Terminal aus, verwenden Sie dann '/login' und folgen Sie den Anweisungen. Aktualisieren oder starten Sie diese App anschließend neu.",
    codex_token_expired_title: "Codex-Authentifizierungsfehler",
    codex_token_expired_body: "Fuhren Sie 'codex' in einem Terminal aus und folgen Sie den Anmeldeanweisungen. Aktualisieren oder starten Sie diese App anschliessend neu.",
    antigravity_token_expired_title: "Antigravity-Authentifizierungsfehler",
    antigravity_token_expired_body: "Offnen Sie Antigravity und melden Sie sich erneut an. Aktualisieren oder starten Sie diese App anschliessend neu.",
    codex_window_title: "Codex-Nutzungsmonitor",
    antigravity_window_title: "Antigravity-Nutzungsmonitor",
    second_suffix: "s",
    section_appearance: "Erscheinungsbild",
    section_font: "Schriftart",
    section_size: "Größe",
    section_animations: "Animationen",
    section_update: "Update",
    section_presets: "Voreinstellungen",
    color_calm: "Ruhig",
    color_attention: "Achtung",
    color_critical: "Kritisch",
    color_background: "Hintergrund",
    color_text: "Text",
    color_divider: "Trennlinie",
    frequency_custom: "Benutzerdefiniert",
    preset_default: "Standard",
    preset_glass: "Glas",
    preset_neon: "Neon",
    preset_minimal: "Minimal",
    weight_regular: "Normal",
    weight_semibold: "Halbfett",
    weight_bold: "Fett",
    geometry_height: "Höhe",
    geometry_corner_radius: "Eckenradius",
    geometry_bar_thickness: "Balkendicke",
    geometry_label_width: "Beschriftungsbreite",
    geometry_text_width: "Textbreite",
    geometry_spacing: "Abstand",
    field_opacity: "Deckkraft",
    field_family: "Schriftfamilie",
    field_size: "Größe",
    field_weight: "Schriftschnitt",
    field_on: "Ein",
    field_speed: "Geschwindigkeit",
    field_intensity: "Intensität",
    field_threshold: "Schwellenwert",
    field_duration: "Dauer",
    field_reduce_motion: "Bewegung reduzieren",
    field_frequency: "Häufigkeit",
    field_custom_minutes: "Benutzerdefiniert (Min.)",
    group_fill: "Füllung",
    group_shimmer: "Schimmer",
    group_alert_glow: "Alarmleuchten",
    group_fade_slide: "Ein-/Ausblenden",
    button_reset: "Zurücksetzen",
    button_cancel: "Abbrechen",
    button_save: "Speichern",
    presets_intro: "Klicken Sie auf eine Voreinstellung, um sie auf Erscheinungsbild und Animationen unten anzuwenden. Speichern zum Behalten, Abbrechen zum Verwerfen.",
};
