use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "WinGet で更新";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Code 使用量モニター",
    refresh: "更新",
    update_frequency: "更新間隔",
    one_minute: "1分",
    five_minutes: "5分",
    fifteen_minutes: "15分",
    one_hour: "1時間",
    models: "モデル",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "設定",
    open_settings: "設定…",
    start_with_windows: "Windows と同時に開始",
    reset_position: "位置をリセット",
    language: "言語",
    system_default: "システム既定",
    check_for_updates: "更新を確認",
    checking_for_updates: "更新を確認しています...",
    updates: "更新",
    update_in_progress: "更新確認は既に実行中です。",
    up_to_date: "既に最新バージョンです。",
    up_to_date_short: "最新です",
    update_failed: "自動更新を完了できませんでした",
    applying_update: "更新を適用しています...",
    update_to: "更新先",
    update_available: "更新が利用可能です",
    update_prompt_now: "バージョン {version} が利用可能です。今すぐ更新しますか？",
    exit: "終了",
    show_widget: "ウィジェットを表示",
    session_window: "5h",
    weekly_window: "7d",
    now: "今",
    day_suffix: "日",
    hour_suffix: "時間",
    minute_suffix: "分",
    token_expired_title: "認証エラー",
    token_expired_body: "ターミナルで 'claude' を実行し、'/login' を使って案内に従ってください。その後、このアプリを更新するか再起動してください。",
    codex_token_expired_title: "Codex 認証エラー",
    codex_token_expired_body: "ターミナルで 'codex' を実行し、サインインの案内に従ってください。その後、このアプリを更新または再起動してください。",
    antigravity_token_expired_title: "Antigravity 認証エラー",
    antigravity_token_expired_body: "Antigravity を開いて再度サインインしてください。その後、このアプリを更新するか再起動してください。",
    codex_window_title: "Codex 使用量モニター",
    antigravity_window_title: "Antigravity 使用量モニター",
    second_suffix: "秒",
    section_appearance: "外観",
    section_font: "フォント",
    section_size: "サイズ",
    section_animations: "アニメーション",
    section_update: "更新",
    section_presets: "プリセット",
    color_calm: "穏やか",
    color_attention: "注意",
    color_critical: "重大",
    color_background: "背景",
    color_text: "テキスト",
    color_divider: "区切り線",
    frequency_custom: "カスタム",
    preset_default: "デフォルト",
    preset_glass: "ガラス",
    preset_neon: "ネオン",
    preset_minimal: "ミニマル",
    weight_regular: "レギュラー",
    weight_semibold: "セミボールド",
    weight_bold: "ボールド",
    geometry_height: "高さ",
    geometry_corner_radius: "角の丸み",
    geometry_bar_thickness: "バーの太さ",
    geometry_label_width: "ラベル幅",
    geometry_text_width: "テキスト幅",
    geometry_spacing: "間隔",
    field_opacity: "不透明度",
    field_family: "フォントファミリー",
    field_size: "サイズ",
    field_weight: "太さ",
    field_on: "オン",
    field_speed: "速度",
    field_intensity: "強さ",
    field_threshold: "しきい値",
    field_duration: "長さ",
    field_reduce_motion: "モーションを減らす",
    field_frequency: "頻度",
    field_custom_minutes: "カスタム（分）",
    group_fill: "塗りつぶし",
    group_shimmer: "シマー",
    group_alert_glow: "警告の光",
    group_fade_slide: "フェード / スライド",
    button_reset: "リセット",
    button_cancel: "キャンセル",
    button_save: "保存",
    presets_intro: "プリセットをクリックすると、下の外観とアニメーションに適用されます。保存すると変更が確定し、キャンセルすると破棄されます。",
    rgba_custom: "カスタム…",
    preset_category_builtin: "内蔵",
    preset_category_editors: "コードエディター",
    preset_category_apps: "アプリ",
};
