use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "WinGet으로 업데이트";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Code 사용량 모니터",
    refresh: "새로고침",
    update_frequency: "업데이트 주기",
    one_minute: "1분",
    five_minutes: "5분",
    fifteen_minutes: "15분",
    one_hour: "1시간",
    models: "모델",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "설정",
    open_settings: "설정…",
    start_with_windows: "Windows 시작 시 자동 실행",
    reset_position: "위치 초기화",
    language: "언어",
    system_default: "시스템 기본값",
    check_for_updates: "업데이트 확인",
    checking_for_updates: "업데이트 확인 중...",
    updates: "업데이트",
    update_in_progress: "이미 업데이트 확인이 진행 중입니다.",
    up_to_date: "이미 최신 버전입니다.",
    up_to_date_short: "최신",
    update_failed: "자동 업데이트를 완료할 수 없습니다",
    applying_update: "업데이트 적용 중...",
    update_to: "업데이트 대상",
    update_available: "업데이트 사용 가능",
    update_prompt_now: "버전 {version}을 사용할 수 있습니다. 지금 업데이트하시겠습니까?",
    exit: "종료",
    show_widget: "위젯 표시",
    session_window: "5시간",
    weekly_window: "7일",
    now: "지금",
    day_suffix: "일",
    hour_suffix: "시간",
    minute_suffix: "분",
    token_expired_title: "인증 오류",
    token_expired_body: "터미널에서 'claude'를 실행한 다음 '/login'을 사용하고 안내에 따라 진행하세요. 그런 다음 이 앱을 새로 고치거나 다시 시작하세요.",
    codex_token_expired_title: "Codex 인증 오류",
    codex_token_expired_body: "터미널에서 'codex'를 실행하고 로그인 안내를 따르세요. 그런 다음 이 앱을 새로 고치거나 다시 시작하세요.",
    antigravity_token_expired_title: "Antigravity 인증 오류",
    antigravity_token_expired_body: "Antigravity를 열고 다시 로그인하세요. 그런 다음 이 앱을 새로 고치거나 다시 시작하세요.",
    codex_window_title: "Codex 사용량 모니터",
    antigravity_window_title: "Antigravity 사용량 모니터",
    second_suffix: "초",
    section_appearance: "외관",
    section_font: "글꼴",
    section_size: "크기",
    section_animations: "애니메이션",
    section_update: "업데이트",
    section_presets: "프리셋",
    color_calm: "평온",
    color_attention: "주의",
    color_critical: "위험",
    color_background: "배경",
    color_text: "텍스트",
    color_divider: "구분선",
    frequency_custom: "사용자 지정",
    preset_default: "기본값",
    preset_glass: "글래스",
    preset_neon: "네온",
    preset_minimal: "미니멀",
    weight_regular: "레귤러",
    weight_semibold: "세미볼드",
    weight_bold: "볼드",
    geometry_height: "높이",
    geometry_corner_radius: "모서리 반경",
    geometry_bar_thickness: "막대 두께",
    geometry_label_width: "레이블 너비",
    geometry_text_width: "텍스트 너비",
    geometry_spacing: "간격",
    field_opacity: "불투명도",
    field_family: "글꼴 종류",
    field_size: "크기",
    field_weight: "굵기",
    field_on: "켜기",
    field_speed: "속도",
    field_intensity: "강도",
    field_threshold: "임계값",
    field_duration: "지속 시간",
    field_reduce_motion: "모션 줄이기",
    field_frequency: "주기",
    field_custom_minutes: "사용자 지정(분)",
    group_fill: "채우기",
    group_shimmer: "반짝임",
    group_alert_glow: "경고 광채",
    group_fade_slide: "페이드 / 슬라이드",
    button_reset: "초기화",
    button_cancel: "취소",
    button_save: "저장",
    presets_intro: "프리셋을 클릭하면 아래의 외관과 애니메이션에 적용됩니다. 저장하면 유지되고, 취소하면 취소됩니다.",
    rgba_custom: "사용자 지정…",
    preset_category_builtin: "기본 제공",
    preset_category_editors: "코드 편집기",
    preset_category_apps: "앱",
};
