use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Обновить через WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Монитор использования Claude Code",
    refresh: "Обновить",
    update_frequency: "Частота обновления",
    one_minute: "1 минута",
    five_minutes: "5 минут",
    fifteen_minutes: "15 минут",
    one_hour: "1 час",
    models: "Модели",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Настройки",
    open_settings: "Настройки…",
    start_with_windows: "Запускать вместе с Windows",
    reset_position: "Сбросить позицию",
    language: "Язык",
    system_default: "Системный по умолчанию",
    check_for_updates: "Проверить обновления",
    checking_for_updates: "Проверка обновлений...",
    updates: "Обновления",
    update_in_progress: "Проверка обновлений уже выполняется.",
    up_to_date: "У вас уже установлена последняя версия.",
    up_to_date_short: "Актуальная версия",
    update_failed: "Не удалось обновить автоматически",
    applying_update: "Применение обновления...",
    update_to: "Обновить до",
    update_available: "Доступно обновление",
    update_prompt_now: "Доступна версия {version}. Обновить сейчас?",
    exit: "Выход",
    show_widget: "Показать виджет",
    session_window: "5ч",
    weekly_window: "7д",
    now: "сейчас",
    day_suffix: "д",
    hour_suffix: "ч",
    minute_suffix: "м",
    second_suffix: "с",
    token_expired_title: "Ошибка авторизации Claude Code",
    token_expired_body: "Запустите 'claude' в терминале, затем используйте '/login' и следуйте инструкциям. После этого обновите или перезапустите приложение.",
    codex_token_expired_title: "Ошибка авторизации Codex",
    codex_token_expired_body: "Запустите 'codex' в терминале и следуйте инструкциям для входа. После этого обновите или перезапустите приложение.",
    antigravity_token_expired_title: "Ошибка авторизации Antigravity",
    antigravity_token_expired_body: "Откройте Antigravity и войдите снова. После этого обновите или перезапустите приложение.",
    codex_window_title: "Монитор использования Codex",
    antigravity_window_title: "Монитор использования Antigravity",
    section_appearance: "Внешний вид",
    section_font: "Шрифт",
    section_size: "Размер",
    section_animations: "Анимации",
    section_update: "Обновление",
    section_presets: "Пресеты",
    color_calm: "Спокойный",
    color_attention: "Внимание",
    color_critical: "Критический",
    color_background: "Фон",
    color_text: "Текст",
    color_divider: "Разделитель",
    frequency_custom: "Свой",
    preset_default: "По умолчанию",
    preset_glass: "Стекло",
    preset_neon: "Неон",
    preset_minimal: "Минимал",
    weight_regular: "Обычный",
    weight_semibold: "Полужирный",
    weight_bold: "Жирный",
    geometry_height: "Высота",
    geometry_corner_radius: "Радиус угла",
    geometry_bar_thickness: "Толщина полосы",
    geometry_label_width: "Ширина метки",
    geometry_text_width: "Ширина текста",
    geometry_spacing: "Интервал",
    field_opacity: "Непрозрачность",
    field_family: "Семейство",
    field_size: "Размер",
    field_weight: "Начертание",
    field_on: "Вкл",
    field_speed: "Скорость",
    field_intensity: "Интенсивность",
    field_threshold: "Порог",
    field_duration: "Длительность",
    field_reduce_motion: "Уменьшить анимацию",
    field_frequency: "Частота",
    field_custom_minutes: "Свой (мин)",
    group_fill: "Заливка",
    group_shimmer: "Мерцание",
    group_alert_glow: "Свечение тревоги",
    group_fade_slide: "Затухание / Скольжение",
    button_reset: "Сбросить",
    button_cancel: "Отмена",
    button_save: "Сохранить",
    presets_intro: "Нажмите на пресет, чтобы применить его к разделам «Внешний вид» и «Анимации» ниже. Сохраните, чтобы оставить, или отмените, чтобы отклонить.",
};
