use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Actualizar con WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Monitor de uso de Claude Code",
    refresh: "Actualizar",
    update_frequency: "Frecuencia de actualización",
    one_minute: "1 minuto",
    five_minutes: "5 minutos",
    fifteen_minutes: "15 minutos",
    one_hour: "1 hora",
    models: "Modelos",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Configuración",
    open_settings: "Configuración…",
    start_with_windows: "Iniciar con Windows",
    reset_position: "Restablecer posición",
    language: "Idioma",
    system_default: "Predeterminado del sistema",
    check_for_updates: "Buscar actualizaciones",
    checking_for_updates: "Buscando actualizaciones...",
    updates: "Actualizaciones",
    update_in_progress: "Ya hay una comprobación de actualización en curso.",
    up_to_date: "Ya tienes la versión más reciente.",
    up_to_date_short: "Actualizado",
    update_failed: "No se pudo actualizar automáticamente",
    applying_update: "Aplicando actualización...",
    update_to: "Actualizar a",
    update_available: "Actualización disponible",
    update_prompt_now: "La versión {version} está disponible. ¿Quieres actualizar ahora?",
    exit: "Salir",
    show_widget: "Mostrar widget",
    session_window: "5h",
    weekly_window: "7d",
    now: "ahora",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    token_expired_title: "Error de autenticación",
    token_expired_body: "Ejecuta 'claude' en una terminal, luego usa '/login' y sigue las indicaciones. Después, actualiza o reinicia esta aplicación.",
    codex_token_expired_title: "Error de autenticacion de Codex",
    codex_token_expired_body: "Ejecuta 'codex' en una terminal y sigue las indicaciones de inicio de sesion. Despues, actualiza o reinicia esta aplicacion.",
    antigravity_token_expired_title: "Error de autenticacion de Antigravity",
    antigravity_token_expired_body: "Abre Antigravity e inicia sesion otra vez. Despues, actualiza o reinicia esta aplicacion.",
    codex_window_title: "Monitor de uso de Codex",
    antigravity_window_title: "Monitor de uso de Antigravity",
    second_suffix: "s",
    section_appearance: "Apariencia",
    section_font: "Fuente",
    section_size: "Tamaño",
    section_animations: "Animaciones",
    section_update: "Actualización",
    section_presets: "Preajustes",
    color_calm: "Calma",
    color_attention: "Atención",
    color_critical: "Crítico",
    color_background: "Fondo",
    color_text: "Texto",
    color_divider: "Divisor",
    frequency_custom: "Personalizado",
    preset_default: "Predeterminado",
    preset_glass: "Cristal",
    preset_neon: "Neón",
    preset_minimal: "Minimalista",
    weight_regular: "Normal",
    weight_semibold: "Seminegrita",
    weight_bold: "Negrita",
    geometry_height: "Altura",
    geometry_corner_radius: "Radio de esquina",
    geometry_bar_thickness: "Grosor de la barra",
    geometry_label_width: "Ancho de etiqueta",
    geometry_text_width: "Ancho de texto",
    geometry_spacing: "Espaciado",
    field_opacity: "Opacidad",
    field_family: "Familia",
    field_size: "Tamaño",
    field_weight: "Peso",
    field_on: "Activado",
    field_speed: "Velocidad",
    field_intensity: "Intensidad",
    field_threshold: "Umbral",
    field_duration: "Duración",
    field_reduce_motion: "Reducir movimiento",
    field_frequency: "Frecuencia",
    field_custom_minutes: "Personalizado (min)",
    group_fill: "Relleno",
    group_shimmer: "Destello",
    group_alert_glow: "Resplandor de alerta",
    group_fade_slide: "Desvanecer / Deslizar",
    button_reset: "Restablecer",
    button_cancel: "Cancelar",
    button_save: "Guardar",
    presets_intro: "Haz clic en un preajuste para aplicarlo a Apariencia y Animaciones a continuación. Guardar para conservarlo, Cancelar para descartarlo.",
};
